### ISSUE TITLE
Week-1 Question 4

### ISSUE THREAD

**Issue by LalitKumar-2001** [Arpita-45/LiftOff-C-Assignment-Solutions#1]
Conio and getch are not needed when code is being written using vscode or any other ide except Turbo. Why have you used those in this specific  question only and not in others?

**Comment by LalitKumar-2001** [comment]
Default condition in switch case missing.

**Comment by Arpita-45** [comment]
Ok Bhai I have updated the answers and removed conio.h and getch

**Comment by LalitKumar-2001** [comment]
Ok. Done
